version: '3.8'
services:
  db:
    image: postgres:17.4
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: