version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
      - uploads_data:/opt/app/uploads
    restart: always
    depends_on:
      - db
    networks:
      - main

  db:
    image: postgres:17.4
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data:

  uploads_data: